/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo(private var real: Int=0 , private var imag: Int=0 ) {

    fun inicializar(real:Int,imag:Int){
        this.real=real
        this.imag=imag
    }
    fun mostrar(){
        println(this.toString())
    }
    override fun toString():String{
        return "(${real},${imag})"
    }
    fun sumar(valor: Complejo): Complejo {
        return Complejo(
            real + valor.real,
            imag + valor.imag
        )
    }
    fun restar(valor: Complejo): Complejo {
        return Complejo(
            real - valor.real,
            imag - valor.imag
        )
    }
}

fun main() {
    var complejo: Complejo
    complejo = Complejo(3,4)
    println("mi número complejo es ${complejo.toString()}")

    var c2:Complejo= Complejo(3,6)
    var c3:Complejo= Complejo(1,2)
    c3 = complejo.sumar(c2)
    c3.mostrar()
    c3 = c2.restar(complejo)
    c3.mostrar()

}