/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo(private var real: Double = 0.0, private var imag: Double = 0.0) {

    fun inicializar(real: Double, imag: Double) {
        this.real = real
        this.imag = imag
    }

    fun mostrar() {
        println(this.toString())
    }

    override fun toString(): String {
        return "(${real},${imag})"
    }

    fun sumar(valor: Complejo): Complejo {
        return Complejo(
            real + valor.real,
            imag + valor.imag
        )
    }

    fun restar(valor: Complejo): Complejo {
        return Complejo(
            real - valor.real,
            imag - valor.imag
        )
    }

    // Función de Multiplicación
    fun multiplicar(valor: Complejo): Complejo {
        return Complejo(
            real * valor.real - imag * valor.imag,
            real * valor.imag + imag * valor.real
        )
    }

    // Función de División
    fun dividir(valor: Complejo): Complejo {
        val denominador = valor.real * valor.real + valor.imag * valor.imag
        return Complejo(
            (real * valor.real + imag * valor.imag) / denominador,
            (imag * valor.real - real * valor.imag) / denominador
        )
    }
}

fun main() {
    var complejo: Complejo
    complejo = Complejo(3.0, 4.0)
    println("mi número complejo es ${complejo.toString()}")

    var c2: Complejo = Complejo(3.0, 6.0)
    var c3: Complejo = Complejo()
    
    c3 = complejo.multiplicar(c2)
    c3.mostrar()
    
    c3 = c2.dividir(complejo)
    c3.mostrar()
}