/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Complejo{
    private var imaginario: Int = 0
    private var real: Int = 0
    private var suma: String = ""
    fun inicialize(real: Int, imaginario: Int){
        this.real = real
        this.imaginario = imaginario
    }
    fun return_value_real(): Int{
        return real
    }
    fun return_value_imagine(): Int{
        return imaginario
    }
    fun return_in_str(): String{
        return "($real + $imaginario i)"
    }
    fun return_to_suma(value: String) {
        this.suma = value
    }
    fun show_suma(): String {
        return this.suma
    }
}

fun main() {
    val app: Complejo
    app=Complejo()
    app.inicialize(5, 2)
    println(app.return_value_real())
    println(app.return_value_imagine())
    println(app.return_in_str())
    app.return_to_suma(app.return_in_str())
    println(app.show_suma())
}
/*
    # 2026-numeros-complejos

    # Clase Complejo - Ejercicio

    ## Descripción

    Se pide crear una clase llamada `Complejo` que represente un número complejo.

    ## Requisitos

    1. **Atributos privados**: La clase debe tener dos atributos privados:
    - `reale`: parte real del número complejo
    - `imaginario`: parte imaginaria del número complejo

    2. **Método para mostrar**: Implementar una función que retorne el número complejo en formato:
    ```
    (real, imaginario)
    ```

    3. **Ejemplo de uso**

    ```python
    c = Complejo(3, 4)
    print(c.mostrar())  # Salida: (3, 4)
    ```     
 */
